title: Little Dream
tagline: Kandalama, Dambulla
email: littled_dambulla@yahoo.com
phone: "+94 77 1849775"
description: >
   Little dream Kandalama is beautiful and tranquil guest house and garden, 
   tucked away in a little corner of paradise near the shores of lake 
   Kandalama. Come here to relax in peace with only the sounds of the birds, 
   or as a base from which to visit attractions in the surrounding area.
baseurl: ""
url: "http://littledreamdambulla.com"
markdown: kramdown
collections:
  attractions:
    output: true
    permalink: /attraction/:path/
  activities:
    output: true
    permalink: /activity/:path/
